### ISSUE TITLE
Python client silently ignores data larger than one UDP datagram

### ISSUE THREAD

**Issue by tzickel** [jaegertracing/jaeger-client-python#128]
A. The documentation does not specify that there is any limit on data sizes and/or what happens in such a case (not sure that all users of this package are versed in UDP Transport and it's limitations).
B. The code does not handle python socket send exceptions (UDP throws an exception on a send larger than one datagram size, at least on linux).
C. The metrics counters do not count spans which were discarded because of UDP size limits anywhere.

**Comment by yurishkuro** [comment]
+1, should be fixed. Would you be able to submit a PR?

**Comment by tzickel** [comment]
I am not versed at jaeger at all (A friend just asked me why he doesn't see some of the spans he is sending, and I figured you are using UDP as a backend.) so I rather someone who actually knows / uses it handle it.

**Comment by ror6ax** [comment]
This is an interesting one. Slicing the batch would not make much sense due to the nature of UDP. In my opinion the right approach is to modify _consume_queue and _make_jaeger_batch to accept a batch size parameter depending on MTU. Or just setting some limit on a batch. @yurishkuro - what are your thoughts?

**Comment by yurishkuro** [comment]
We do emit metrics and logs if UDP send fails

https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/reporter.py#L201

The main thing about Python client is that it's not written the same way as other clients which actually pre-compute the expected size of the batch and manage flush w.r.t. that size vs. the MAX_PACKET_SIZE (65000 bytes by default - MTU is not relevant for loopback comms). Instead Python client simple looks for the fixed # of spans as the indicator to flush. This worked well for us because that batch size is fairly small (10) and our average span size in Python is <1kb, so we have plenty of room in the buffer.

**Comment by ror6ax** [comment]
Well, it looks like it does not work all the time ;) I can look into sizing up the batch before sending it out. Should I?

**Comment by yurishkuro** [comment]
If you do, that would be a pretty large change, effectively reimplementing the whole architecture of the senders API. I would rather have the confirmation first that there is indeed an issue (the person who filed a ticket said "asked for a friend"), and maybe simply adjust the docs. I.e. I would start with a unit test that writes large batch and see what metrics/logs are emitted.

**Comment by tzickel** [comment]
1. My friend increased the default reporter_queue_size from 100 to 10000 and it fixed most? of his issues.
2. If you send 1 span with a log message that is very long (maybe it's unlikely, but still) that is close to a datagram size, it still fails. (IIRC it does not end up in any metrics counter).
