### ISSUE TITLE
Module not found in Windows 10

### ISSUE THREAD

**Issue by fabianobr** [jaegertracing/jaeger-client-python#189]
I need to solve a non functional requirement, to work on windows 10.

I can't work in an windows 10 environment.

Traceback (most recent call last):
  File "D:\utils\jaeger\tracer.py", line 3, in <module>
    from jaeger_client import Config
  File "C:\Python36\lib\site-packages\jaeger_client\__init__.py", line 26, in <module>
    from .tracer import Tracer  # noqa
  File "C:\Python36\lib\site-packages\jaeger_client\tracer.py", line 33, in <module>
    from .utils import local_ip
  File "C:\Python36\lib\site-packages\jaeger_client\utils.py", line 17, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

Do we have any alternative to mitigate this?

**Comment by yurishkuro** [comment]
this happens when the client tries to determine IP address of the host to record it in the span. You can pass the IP in a tag to the tracer:
```
jaeger_client/constants.py:51:JAEGER_IP_TAG_KEY = 'ip'
```
then the client will not be doing the lookup. It might still blow up since utils.py imports these at the top, it could be addressed by moving imports inside `interface_ip()` function. To do this correctly it may need windows-specific code (unless there's a polyfill somewhere)

**Comment by ZmeiGorynych** [comment]
Thanks! Ran into the same thing.
It seems a bit harsh for the code to fail on Windows because of this, would it not make more sense to return an IP of 'Unknown IP' or something like that? 
Happy to submit a pull request for that.

**Comment by yurishkuro** [comment]
PRs are always welcome
