### ISSUE TITLE
tracer.inject with Format.BINARY is always empty

### ISSUE THREAD

**Issue by nicholasamorim** [jaegertracing/jaeger-client-python#224]
## Requirement - what kind of business use case are you trying to solve?

Injecting context data via tracer.inject in binary format. Trying to make the python cassandra driver compatible with [cassandra zipkin tracer](https://github.com/thelastpickle/cassandra-zipkin-tracing) by propagating context to Cassandra too.

## Problem - what in Jaeger blocks you from solving the requirement?

```python
carrier = bytearray()  # always empty
tracer.inject(span, Format.BINARY, carrier)
```

I tried adapting the files in [Solution 3 of the tutorial](https://github.com/yurishkuro/opentracing-tutorial/tree/master/python/lesson03/solution) as well but binary is also empty.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I'm not really sure what causes the problem because TEXT_MAP or HTTP_HEARDS work just fine and return a `uber-trace-id`.

## Any open questions to address

opentracing==2.0.0
opentracing-instrumentation==2.4.3
Using this jaeger: `-e git+https://github.com/yurishkuro/jaeger-client-python.git@d631596415cb549a4e8314cc25d6c53fab710528#egg=jaeger_client`

**Comment by black-adder** [comment]
Ah, looks like the binary codec is not currently implemented: https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/codecs.py#L139

Would you be willing to contribute the implementation? This is the golang implementation for injection: https://github.com/jaegertracing/jaeger-client-go/blob/f7e0d4744fa6d5287c53b8ac8d4f83089ce07ce8/propagation.go#L169

**Comment by nicholasamorim** [comment]
Hey @black-adder thanks for the anwer.

I'll try and port the GO version.

**Comment by nicholasamorim** [comment]
I have an initial implementation that works-ish. The basic injecting works but the baggage one doesn't seems to work.

I've never worked with binary data before as well so I might be far off mark here. @black-adder could you do a quick review of this work-in-progress?

```python
class BinaryCodec(TextCodec):
    def inject(self, span_context, carrier):
        if not isinstance(carrier, bytearray):
            raise InvalidCarrierException('carrier not a bytearray')

        self.append(carrier, span_context.trace_id)
        self.append(carrier, span_context.span_id)
        if span_context.parent_id:
            self.append(carrier, span_context.parent_id)
        if span_context.flags:
            # print 'Flags', span_context.flags
            self.append(carrier, span_context.flags)

        if span_context.baggage:
            self.append(carrier, len(span_context.baggage))
            for k, v in six.iteritems(span_context.baggage):
                self.append(carrier, len(k))
                self.append(carrier, k)
                self.append(carrier, len(v))
                self.append(carrier, v)

        carrier[self.trace_id_header] = span_context_to_string(
            trace_id=span_context.trace_id, span_id=span_context.span_id,
            parent_id=span_context.parent_id, flags=span_context.flags)
        baggage = span_context.baggage
        if baggage:
            for key, value in six.iteritems(baggage):
                encoded_key = key
                if self.url_encoding:
                    if six.PY2 and isinstance(value, six.text_type):
                        encoded_value = urllib_parse.quote(value.encode('utf-8'))
                    else:
                        encoded_value = urllib_parse.quote(value)
                    # we assume that self.url_encoding means we are injecting
                    # into HTTP headers. httplib does not like unicode strings
                    # so we convert the key to utf-8. The URL-encoded value is
                    # already a plain string.
                    if six.PY2 and isinstance(key, six.text_type):
                        encoded_key = key.encode('utf-8')
                else:
                    if six.PY3 and isinstance(value, six.binary_type):
                        encoded_value = str(value, 'utf-8')
                    else:
                        encoded_value = value
                if six.PY3 and isinstance(key, six.binary_type):
                    encoded_key = str(key, 'utf-8')
                # Leave the below print(), you will thank me next time you debug unicode strings
                # print('adding baggage', key, '=>', value, 'as', encoded_key, '=>', encoded_value)
                header_key = '%s%s' % (self.baggage_prefix, encoded_key)
                carrier[header_key] = encoded_value

    def extract(self, carrier):
        if not isinstance(carrier, bytearray):
            raise InvalidCarrierException('carrier not a bytearray')
        # TODO binary encoding not implemented
        return None

    def to_bytes(self, n, length, endianess='big'):
        if six.PY3:
            return n.to_bytes(length, endianess)
        else:
            h = '%x' % n
            s = ('0' * (len(h) % 2) + h).zfill(length * 2).decode('hex')
            return s if endianess == 'big' else s[::-1]

    def append(self, carrier, value, length=8):
        if isinstance(value, six.integer_types):
            value = self.to_bytes(value, length)

        carrier += value
```

**Comment by yurishkuro** [comment]
I see several issues here. First, Cassandra zipkin tracer is, well, a **zipkin** tracer. I don't know if there's a similar OpenTracing version, eg in opentracing-contrib. If not, it would probably make sense to take the one from lastpickle and refactor to use OpenTracing API. Then it would actually make sense to talk about binary codec.

Second, I don't know if binary codec is even necessary. Does Cassandra protocol pass tracing context as an opaque blob of bytes, or via someore general key/value metadata? If the latter, you'd be better off using text map.

Assuming it only allows a binary blob, you could still use text map codec, eg by encoding the map into a String, json or newline separated. But at this point it makes sense to talk about binary codec.

Jaeger hasn't officially supported binary codec because there weren't real use cases where it was necessary. But the go client does implement it and should be used as reference implementation (I doubt the spec is written for it, but the code is pretty obvious). I don't recall if java client has one. And I don't know what the situation is with 128bit trace IDs, because I remember writing Go codec when we only supported 64bit.

This brings me to third issue - the values from the context must be encoded with precise bit lenghts and correct endianness.

Last issue - we don't have any compatibility integration tests for binary codecs in different languages, we only have http.

So that's a lot. If you want just a quick solution, you may want to stick with the lastpickle tracer, figure out how exactly it encodes span context (ignore baggage), and implement a custom codec for that. It won't be "binary codec for Jaeger".

HTH.

**Comment by nicholasamorim** [comment]
That makes sense, that's why I was having difficulties conciliating both ends of this operation. That expects the Zipkin B3 format.

The initial work for the scope of my use case is indeed convert zipkin tracer from TLP. I'll take a look into their code and see how to migrate to OT. I have seen it before and it's certainly small and simple, so that's an effort I might be willing to undertake.

I will check this out and see if it's okay to simply transfer the context as `text map` and operate on that on the plugin side. If binary is necessary, I'll check this again but certainly in a different light.

Not sure if it makes sense to keep this open for now.

Thanks a lot @yurishkuro

**Comment by gionapaolini** [comment]
I'm having the same issue, is there an update on this?
