### ISSUE TITLE
OpenFaas - serverless functions

### ISSUE THREAD

**Issue by FlorianKuckelkorn** [jaegertracing/jaeger-client-python#229]
Hi,

i am using the jaeger python client library in my serverless functions run with OpenFaaS on Docker Swarm.
So far it does work, but calling tracer.close only works if  i put time.sleep behind it :(
I Included the tracing stuff inside the request handler of the serverless function.

That time.sleep does increase function execution time extremly!
Is there a way to solve this in a more reliable and more time efficent manner?

Thanks in Advance

**Comment by yurishkuro** [comment]
you need a fix for #50

**Comment by bhavin192** [comment]
We faced same issue while implementing tracing for Fission's Python Environment. As yurishkuro said here https://github.com/jaegertracing/jaeger-client-python/issues/50#issuecomment-394922333, I'm just creating tracer once for lifetime of the function. In Fission if there are no requests for certain amount of time, the Pod where function code is running gets killed, so that works for now. i.e. Create the Tracer and never close it.
You can take a look at the code here https://github.com/bhavin192/fission/blob/python-env-opentracing/environments/python/lib/tracing.py

**Comment by alexellis** [comment]
Hi, did you get a resolution for this? Maybe it's something the project team can help with if you ask on Slack? https://docs.openfaas.com/community

Alex

**Comment by yurishkuro** [comment]
as I said, the resolution would be to fix #50

**Comment by FlorianKuckelkorn** [comment]
Hi,
i only worked out a indirect solution. @alexellis as you suggested here: https://github.com/openfaas/faas/issues/1004

i switched to the of-watchdog with flask an initilaized the jaeger client globally like bhavini92 in fission did.
Seems to work :) But in general fixing #50 seems to be a good idea

THanks so far
