### ISSUE TITLE
ModuleNotFoundError: No module named 'jaeger_client'

### ISSUE THREAD

**Issue by AYEG** [jaegertracing/jaeger-client-python#234]
## Requirement - what kind of business use case are you trying to solve?
Trying to use jeager_client for the first time within a flask application and I'm receiving this import error
`ModuleNotFoundError: No module named 'jaeger_client`

It was installed with the command:
>  pip install jaeger-client
  within an active conda environment and like other packages I can see it is installed at the correct location. 
>  /project-name/bin/python

There is an __init__.py in the folder and setting up another module such as Sentry in the same file which works fine. 

## Problem - what in Jaeger blocks you from solving the requirement?
I can't import the module. Could this be a naming issue? e.g. with the lower dash

Using:
Python 3.6.6 
pip 18.1

**Comment by pravarag** [comment]
Can u check in your pip freeze output whether jaeger-client and opentracing are installed or not?

**Comment by pravarag** [comment]
> ## Requirement - what kind of business use case are you trying to solve?
> Trying to use jeager_client for the first time within a flask application and I'm receiving this import error
> `ModuleNotFoundError: No module named 'jaeger_client`
> 
> It was installed with the command:
> 
> > pip install jaeger-client
> > within an active conda environment and like other packages I can see it is installed at the correct location.
> > /project-name/bin/python
> 
> There is an **init**.py in the folder and setting up another module such as Sentry in the same file which works fine.
> 
> ## Problem - what in Jaeger blocks you from solving the requirement?
> I can't import the module. Could this be a naming issue? e.g. with the lower dash
> 
> Using:
> Python 3.6.6
> pip 18.1

no, it can't be a naming issue as imports in Python are mostly declared using '_' only. I faced a similar situation running jaeger in a containerized environment. So for that actually I was using requirements.txt from here [opentracing jaeger-client-python](https://github.com/yurishkuro/opentracing-tutorial/blob/master/python/requirements.txt) . I had to remove every other installation of jaeger-client and opentracing and install just this line "-e git+https://github.com/yurishkuro/jaeger-client-python.git@d631596415cb549a4e8314cc25d6c53fab710528#egg=jaeger-client" & it worked. But again, this was strange since it points to an older version

**Comment by AYEG** [comment]
Thanks for helping out that resolved the error, I'll give jaeger another try soon!
