### ISSUE TITLE
Drop Python2 support

### ISSUE THREAD

**Issue by approximator** [jaegertracing/jaeger-client-python#259]
## Requirement - what kind of business use case are you trying to solve?

Reduce development and maintenance load by dropping support of Python2

## Problem - what in Jaeger blocks you from solving the requirement?

Having to support both Python2 and Python3 increases the amount of effort needed for fixing existing issues.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Drop support of Python2

## Any open questions to address

What do you think about this?

**Comment by approximator** [comment]
Python2 will be discontinued on January 1, 2020
https://www.python.org/doc/sunset-python-2/

So, is there any reason to support it here?

**Comment by yurishkuro** [comment]
End of official support doesn't mean people would immediately stop using it. Supporting 2.x in this lib is not such a large effort.

**Comment by abhinavg97** [comment]
#310 Removing six would mean jaeger_client no longer supports python2 since the urllib module is not available for python2. @yurishkuro

**Comment by yurishkuro** [comment]
python2 support has been removed

**Comment by ktoolss** [comment]
@yurishkuro Hi, I'm new to configuring. I'm trying to use "from jaeger_client import Config" in a python 2.7 app, but I'm getting this error 

with tracer.start_active_span('say-hello') as scope:
AttributeError: 'NoneType' object has no attribute 'start_active_span'

Is this because python2 support ended? Would you be able to recommend which versions of jaeger client and opentracing I can use in python 2.7?

Thank you for your time and help

**Comment by yurishkuro** [comment]
you can check the changelog to see in which version this PR was merged, and use the version before that.
