### ISSUE TITLE
Support sending spans over HTTP

### ISSUE THREAD

**Issue by wkiser** [jaegertracing/jaeger-client-python#98]
Similar to the [HttpSender](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/senders/HttpSender.java) in jaeger-java. It seems like it could be as simple as using THttpClient in place of TUDPTransport and  connecting to the collector directly. I'm happy to help out with the implementation if needed.

Background: I have some applications that are generating huge spans (> 65k) because they are including full SQL and ES queries as logs in the trace. Right now we are manually truncating the queries, but my clients would like to be able to view them for debugging purposes.

**Comment by ProvoK** [comment]
It would be nice to have this possibility. It will enable to trace in context where is not possible to have an agent installed, for example a Lambda (AWS) function. 
Is this in development?

**Comment by yurishkuro** [comment]
not aware of anyone working on it. Contributions are welcome.

**Comment by ProvoK** [comment]
Here I am, sorry for the delay.

After some investigation on the code with the help of @black-adder, I started a refactor to make this change in a clean way. So it's all still a **WIP**, and I would like to have some feedbacks 

## Work done [[compare]](https://github.com/jaegertracing/jaeger-client-python/compare/master...ProvoK:send_spans_over_http)
So, there are quite a lot of changes, because things were a bit entangled.

1.  I extracted the duty of sending batches from the `Reporter` class, which now delegates to a **injected** ( via \_\_init\_\_ )  `Sender` subclasse (senders.py). There is actually only one real implementation of the `Sender`, which is `UDPSender`, aka sending via a local agent. 
    * `senders.HTTPSender` **will be** the agent-less sender.

2. I removed `local_agent_net.LocalAgentSender.request_sampling_strategy` method, because actually it were mixing responsibilities: now `LocalAgentSender` really does the reporting (and nothing more) whilst `LocalAgentHTTP` is (still) responsible for the sampling. 

3. Refactored `config` for
    * Injecting a `Sender` class to `Reporter` (`UDPSender` if `config.local_agent_enabled` True else `HTTPSender`. Idk if it's correct, could be done more explicitly with a config ad hoc parameter)
    * passing to `RemoteControlledSampler` a really only-sampling capabilities `channel`. Before it was a `LocalAgentSender`, but it used only its sampling capabilities!
    * Deleted `_create_local_agent_channel` which is now `senders.UDPSender` job

I fixed also test accordingly (else if there is a crossdock test that fail...I don't get what's wrong) [Travis](https://travis-ci.org/ProvoK/jaeger-client-python)



## Next steps
1. Make CI full-green
2. Implement Sender unit tests (?)
3. I would like to rename/refactor `local_agent_net` module and it's classes names. 
    * `LocalAgentSender` -> fine
    * `LocalAgentHTTP` -> `RemoteSampler` (or just something that indicates its sampling duties)
4. Implement `senders.HTTPSender.send`
5. Add end to end crossdocks agent-less tests
6. Add documentation for this change

**Comment by ProvoK** [comment]
@yurishkuro Sure, I was thinking about splitting it too.

So I can just remove the actual `HTTPSender` (which is a placeholder) and just PR with the actual refactoring? Of course I'll have to fix the crossdock test that is failing.
About that, how can I debug that error a bit more? It just show [this](https://travis-ci.org/ProvoK/jaeger-client-python/jobs/381330676#L1641) and nothing more

**Comment by yurishkuro** [comment]
Yes, putting a PR with refactoring is the best way forward, we can't really review another branch (no place to leave comments).

Ideally you should not need to change in the crossdock code, because if you do it means your change is not backwards compatible.

The best way to troubleshoot the errors is to run crossdock locally (`make crossdock-fresh`, I believe), and then look at the logs via `make crossdock-logs`.

**Comment by mstump** [comment]
Is this effort dead?

**Comment by yurishkuro** [comment]
no - https://github.com/jaegertracing/jaeger-client-python/pull/186

**Comment by r0fls** [comment]
@yurishkuro is https://github.com/jaegertracing/jaeger-client-python/pull/208 still being considered?

**Comment by ishrivatsa** [comment]
Is this still going on ? I saw that there was a commit pertaining to http support which was removed. I want to use tracing within Serverless functions like AWS Lambda or Azure functions. I cant use UDP for this. Could you please provide more info ?

**Comment by v-yzakapko** [comment]
Hey! Is there some news about it. I need to use tracing via HTTP and it will be good to use it with OT. Maybe somebody has any idea how to implement it using the https://github.com/open-telemetry/opentelemetry-python or combining opentelemetry and opentracing?

**Comment by yurishkuro** [comment]
@v-yzakapko you can try OTEL->OT bridge (I have not tried it myself)

https://github.com/open-telemetry/opentelemetry-python/blob/04a9533ec6b8f5bbe2d41efc1ba1e92e51f1ca74/docs/examples/opentracing/README.rst

**Comment by ptrhck** [comment]
This would be a great feature! Is there any other Python opentracing client that can send spans over HTTP to Jaeger collector?

**Comment by CiCi503** [comment]
Is this still going on ?  I want to use tracing within Serverless functions too, I can not tracing via UDP.

**Comment by tx19980520** [comment]
> Is this still going on ? I saw that there was a commit pertaining to http support which was reverted. I want to use tracing within Serverless functions like AWS Lambda or Azure functions. I cant use UDP for this. Could you please provide more info ?

Have you found an alternative solution now?

**Comment by ptrhck** [comment]
You can use OpenTelemetry as the client: https://opentelemetry-python.readthedocs.io/en/stable/exporter/jaeger/jaeger.html
